### ISSUE TITLE
「エンジニアを褒めるネコ」の追加

### ISSUE THREAD

**Issue by tsmd** [fukayatsu/lttm-crx#64]
使いたい
https://twitter.com/kobaka7/status/937517293604454400

**Comment by fukayatsu** [comment]
@tsmd `!n` という記法で対応してstoreにpublishしたので、あと1時間以内には使えるようになるかと思います


![エンジニアを褒めるネコ:リリースしました](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/35_%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F.png)

**Comment by tsmd** [comment]
雑なIssue立てだったのにも関わらず対応くださりありがとうございました ✨ 
仕事にプライベートに活用させまくります！！

![エンジニアを褒めるネコ:神](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/11_%E7%A5%9E.png)
