### ISSUE TITLE
絵文字選択パネルがレビュー送信モーダルの後ろに隠れてしまう

### ISSUE THREAD

**Issue by kyu08** [fukayatsu/lttm-crx#85]
LTTMを開発・メンテナンスしてくださりありがとうございます！
コードレビューの際によく使わせてもらっています！

表題の通りですがGitHubの1,2週間前のリリースで絵文字選択パネルがレビュー送信モーダルの後ろに隠れるようになってしまいました。

もし可能でしたら修正いただけると大変ありがたいです。（自分でも直してみようとしたのですが`npm i`実行時に node-gyp のエラーが解決できずに断念してしまいました... 🙏）

<img width="825" alt="image" src="https://github.com/fukayatsu/lttm-crx/assets/49891479/1aeed19f-c2d8-421b-8836-23a1c0e2efec">

**Comment by kaibadash** [comment]
なんとか直せないか調べていたのですが、なかなかむつかしい問題でした。
調査結果を記載しておきます。

現状のGitHubのpopupはz-indexを使用したものではなく[Top Layer](https://developer.mozilla.org/ja/docs/Glossary/Top_layer)を使用したもので、z-indexを大きくするだけでは対応できませんでした。
Top Layer上でGitHubのpopupの上に表示させる必要がありそうで、するとPopupを表示しているライブラリを更新すれば良さそうかなと思い調べ始めました。

現状利用されているのが [jquery-atwho](https://github.com/fis-components/jquery-atwho) です。
[Caret.js](https://github.com/ichord/Caret.js) に依存しています。At.jsをベースに実装されている様子。
[At.js](https://github.com/ichord/At.js) はメンテ終了。[Tribute](https://github.com/zurb/tribute) を使えと言っているようです。
Tributeも3年前が最後のコミットで (example)[https://zurb.github.io/tribute/example/] を見てもTop Layerを意識したものではなさそうでダメそうでした。

# その他の問題

そもそもM1ではビルドが困難でした。 https://github.com/fukayatsu/lttm-crx/pull/86

**Comment by fukayatsu** [comment]
@kyu08 @kaibadash ご報告、調査どうもありがとうございます。大変助かりました。反応が遅くなりすみません。

かなり無理矢理な対応なのですが、 https://github.com/fukayatsu/lttm-crx/pull/88/commits/22dec68daae01bcb9262c3e2d39e30e2dd9d9860 で一旦改善されそうなのでこのあとリリースしたいと思います

**Comment by kyu08** [comment]
@fukayatsu 
とんでもないです。修正いただきありがとうございます！
リリースを楽しみに待ちたいと思います。

**Comment by kaibadash** [comment]
![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)

**Comment by fukayatsu** [comment]
![エンジニアを褒めるネコ:リリースしました](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/35_%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F.png)
