### ISSUE TITLE
`v0.4.2`のインストールが完了しない

### ISSUE THREAD

**Issue by kyu08** [fukayatsu/lttm-crx#91]
修正版のリリース、ありがとうございました！
インストールを試みてみましたが、うまくいかなかったので報告させていただきます。🙇

## 行ったこと、起きたこと
1. 拡張機能を削除
1. [Web store](https://chromewebstore.google.com/detail/lttm/jdidcgkdggndpodjbipodfefnpgjooeh)上で「Chromeに追加」をクリック
1. 下記画像のエラーが表示（`Could not decode image: 'icon_128.png'`）
1. エラーメッセージ右側のOKを押下
1. しばらく待ってもインストールが完了せずローディングスピナーが表示されたままだった

![image](https://github.com/user-attachments/assets/7bdbde54-1dbd-4b2e-bfa6-f79b2f9aedeb)

## 動作環境
OS: mac
Brave v 1.73.89

### ["Could not decode image: 'primary.png'" when installing chrome extension](https://stackoverflow.com/questions/65350139/could-not-decode-image-primary-png-when-installing-chrome-extension)
>  I think I just republished the extension without changing anything, and that fixed it. 

このコメントによると拡張機能に変更を加えずに再度publishしたところ問題が解決されたようです。

**Comment by fukayatsu** [comment]
ご報告ありがとうございます。
手元のchromeでもインストール時のエラーを確認しました。

調査したところ、gulpのアップデートの影響で実際にストアに提出した画像ファイルが壊れていたようです。

修正して再度ストアにv0.4.3を申請しました。

**Comment by kyu08** [comment]
早速のご対応ありがとうございます！！

ストア審査が完了した頃に再度試してみようと思います🙇‍♂️

**Comment by kyu08** [comment]
@fukayatsu 
無事に`v0.4.3`をインストールできました！久々に利用できて嬉しいです！
ご対応いただきありがとうございました🙇‍♂️

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/4c6e0d4b-c6af-458b-8821-2e9368c58a6e">

**Comment by fukayatsu** [comment]
![寿司ゆき:congrats](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/64.png)
